### ISSUE TITLE
Inconsistent handling of NULL expressions

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/glue#45] opened 2017-06-24 14:24 UTC
When any expression (but the last) is NULL then ```glue``` returns an empty character vector. In case the last expression is NULL it ignores the last expressions and returns the result of the other expressions.

``` r
library(glue)

empty <- c()
glue(empty, 1)
glue(1, empty)
#> 1
glue(1, 2, empty)
#> 12
glue(1, empty, 0)

glue("{empty}", 1)
glue(1, "{empty}")
glue(1, "{empty}", 0)
```

**Comment by egnha** [comment] 2017-07-10 16:28
@mgirlich This indeed seems to be an inconsistency. But what are you proposing the expected behavior to be? (That's not explicit in your PR, as far as I can tell.)

**Comment by egnha** [comment] 2017-07-11 04:09
@jimhester Should `glue` behave like `paste0` when passing multiple strings? (That would be my naive expectation.) If so, then the examples do seem to be bugs.

**Comment by mgirlich** [comment] 2017-07-11 05:46
@egnha The intention of the PR is that `character()` is returned when any of the interpolated values is `NULL`. I think the behaviour of `paste` is rather unfortunate. This is also similar to #28.

**Comment by egnha** [comment] 2017-07-11 07:17
@mgirlich I think it makes sense that `glue("Annihilated by {empty}", empty = character(0))` should be empty (if the behavior of `sprintf()` is to be mimicked). But the PR seems to be incompatible with the notion of “gluing”/“pasting”: `paste0("a", character(0), "b")` gives `"ab"`, which is consistent with “pasting,” and arguably `glue()` should mimic that. That behavior seems more in line with (my) naive expectations.

I think #28 concerns quite a different matter. It is helpful to think of `paste()` without the `collapse` option, and `paste()` with the `collapse` option, as two very different functions. In my understanding, the point of having the separate function `glue::collapse()` is to disambiguate the unfortunate conflation of these two kinds of pasting in base R.

**Comment by jimhester** [comment] 2017-07-11 16:30
Closed by https://github.com/tidyverse/glue/commit/b945cd166c8d66d626a00554c08dcedc4401cbbf

**Closed by jimhester** 2017-07-11 16:30 UTC

**Comment by egnha** [comment] 2017-07-11 18:18
@jimhester With this change, `glue()` seems to be more consistent with `sprintf()`, which returns 0-length output when a substitution argument has 0-length. On the other hand, `glue()` is now incompatible with `paste0()`, and at odds with its own documentation (“`...` Expressions string(s) to format, multiple inputs are concatenated together before formatting”—I read “concatenated” in the colloquial sense, which is what `paste0()` happens to produce).

I hope I am not flogging a dead horse, but it seems to me that concatenation is an essentially _additive_ operation. In that vein, it seems reasonable that an empty object (`NULL`, `character(0)`) should be treated as an additive _identity element_; in particular, they should not have the effect of annihilating the entire output (despite the historical behavior of `sprintf()` to do otherwise).

**Comment by russellpierce** [comment] 2017-09-27 16:09
I came in with @egnha 's expectation.  I.e. that if an arg were NULL that would be the same as having passed "".  When I'm gluing together SQL I have optional sections, e.g. include a LIMIT/don't include a LIMIT.  It is only natural to put the entire statement together as "LIMIT 10" or NULL.  Instead with current behavior it is "LIMIT 10" or "".  I guess it is this way for 'safety', but it is a bit unexpected. ¯\_(ツ)_/¯
