### ISSUE TITLE
glue_col() only works if crayon is attached

### ISSUE THREAD

**Issue by jennybc** [tidyverse/glue#196] opened 2020-06-18 22:35 UTC
``` r
isNamespaceLoaded("crayon")
#> [1] TRUE
"crayon" %in% .packages()
#> [1] FALSE

glue::glue_col("{blue BLUE!}")
#> Error in get(fun, envir = envir, mode = "function"): object 'blue' of mode 'function' was not found

isNamespaceLoaded("crayon")
#> [1] TRUE
"crayon" %in% .packages()
#> [1] FALSE

library(crayon)

isNamespaceLoaded("crayon")
#> [1] TRUE
"crayon" %in% .packages()
#> [1] TRUE

glue::glue_col("{blue BLUE!}")
#> BLUE!
```

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jennybc** [comment] 2020-06-18 23:01
I suppose this might be a duplicate of #138 and I'm supposed to import specific crayon color functions into my package.

If that is the deal, are you open to a PR to the docs? To make it explicitly clear that, by design, you need to import specific crayon functions or attach crayon to use `glue_col()`. That wasn't clear to me.

**Comment by jimhester** [comment] 2020-08-26 13:45
Yes, it is a duplicate of #138. Sure, would be happy for a PR in the docs.

**Closed** 2021-11-24 21:42 UTC
Labels: documentation
