### ISSUE TITLE
glue_sql handling POSIXct object 

### ISSUE THREAD

**Issue by readerwei** [tidyverse/glue#322] opened 2024-02-23 18:10 UTC
glue package released a new version 1.7.0 recently. It has a breaking change in the glue_sql function. 
glue_sql's handling of POSIXct object is changed from the previous version. 

```r
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
glue::glue_sql("select foo from bar where time = {as.POSIXct('2024-02-12 12:01:01.456789')}", .con=con)
```
Expected output (also output from previous version 1.6.2):
<SQL> select foo from bar where time = '2024-02-12 12:01:01.45678'

Actual output:
<SQL> select foo from bar where time = '20240212120101'

**Comment by jennybc** [comment] 2024-02-23 21:53
Duplicate of #321 which turns out is not a glue issue but rather https://github.com/r-dbi/DBI/issues/467.

**Closed by jennybc** 2024-02-23 21:53 UTC
